# Build & run the bqt command inside the container
FROM golang:1.19.0-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/bqt ./

CMD ["bqt"]
